sudo: false
language: node_js
node_js: ['10']
before_script:
  - npm install
  - npm install -g yarn
script:
  - yarn build:lib
  - cp README.md dist/common
  - cp LICENSE dist/common
  - npm pack
cache:
  directories:
    - node_modules
after_success:
  - cd dist/common
  - npm publish
deploy:
  - provider: releases
    api_key: '$GITHUB_TOKEN'
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    local_dir: dist/common/
    api_key: '$NPM_TOKEN'
    on:
      tags: true